### ISSUE TITLE
Large folder will not open

### ISSUE THREAD

**Issue by Nicodemus75** [nelu/rutorrent-filemanager#13] opened 2021-04-15 01:17 UTC
My default /data folder has ~1.5TB of content, including thousands of small items (>5MB files).

All other folders will open without issue, but when I double click my /data folder, the tree flashes briefly and does not open the directory. All other directories seem to open without issue.

**Comment by nelu** [comment] 2021-05-01 14:48
The response is to large. most likely web server restriction because directory listing is too large. also it might crash your browser if you increase the webserver limitations

**Comment by nelu** [comment] 2022-01-12 04:49
The suggestion was to create the torrent with a large ammount of file, for the purpose of checking wheter is server-side limitation (web server, php), and after checking any logs for hints to a possible solution

**Comment by nelu** [comment] 2022-01-14 07:07
Tested with 15000 - 1kb files inside a directory and the listing works properly. 
Closing the issue for now since i cannot reproduce. 
Feel free to reopen the issue if you have more feedback on how to reproduce

**Closed by nelu** 2022-01-14 07:07 UTC
