### ISSUE TITLE
ruTorrent v5: Problems with handleFilesTabMenu() and webui.fls.view = false

### ISSUE THREAD

**Issue by anthonyryan1** [nelu/rutorrent-filemanager#56] opened 2024-11-13 21:55 UTC
webui.fls.view is toggled by a context menu in the other Files tab in the default ruTorrent WebUI.

![Screenshot from 2024-11-08 22-55-53](https://github.com/user-attachments/assets/2a48640b-cd1b-4240-a4e0-d23018268179)

After it has been toggled, so `theWebUI.settings["webui.fls.view"] == false` the context menu errors out in our handelFilesTabMenu.

The specific cause seems to be that `theWebUI.dirs` is empty when it's in this mode. I've come up with a couple workarounds, but I'm not happy with them yet. So I wanted to document the issue in case the fix was obvious to someone else.

If not, I'll put some more time into this in the coming days.

**Comment by nelu** [comment] 2024-11-14 21:01
Will take a look, at a glance, checking thewebUI.dirs sounds like a solution.

Also does the latest release of ruTorrent + filemanager (v5 compat branch) work properly for you?

**Comment by anthonyryan1** [comment] 2024-11-14 22:17
Yes, everything is working well. This is the last issue I'm currently aware of.

**Comment by nelu** [comment] 2024-11-16 19:14
Should be fixed in https://github.com/nelu/rutorrent-filemanager/commit/a86b862a8abf07001b36483b6a5c02fdd4119ac4
The problem is that the rowid is not passed along the call stack, so another ugly workaround had to be added.

**Comment by nelu** [comment] 2024-11-18 03:50
https://github.com/nelu/rutorrent-filemanager/commit/a86b862a8abf07001b36483b6a5c02fdd4119ac4

**Closed by nelu** 2024-11-18 03:50 UTC
Labels: bug
